import Container from "@/components/Container/Container"
import Header from "@/components/Header/Header"
import Sidebar from "@/components/Sidebar/Sidebar"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="grid grid-flow-row-dense grid-cols-6 grid-rows-6 h-screen bg-dark">
        <Sidebar />
        <div className="grid col-span-5 max-sm:col-span-6 h-screen grid-rows-10 max-xl:col-span-6 ">
          <Header />
          <Container>{children}</Container>
        </div>
      </body>
    </html>
  )
}
